// Generated by CoffeeScript 1.8.0
(function() {
  var City, db, dsvdb, models,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dsvdb = require('../index');

  City = (function(_super) {
    __extends(City, _super);

    function City() {
      return City.__super__.constructor.apply(this, arguments);
    }

    City.prototype.model = 'City';

    City.defaults({
      Country: {
        type: 'string',
        "default": ''
      },
      City: {
        type: 'string',
        "default": ''
      },
      Region: {
        type: 'number',
        "default": 0
      },
      Population: {
        type: 'number',
        "default": 0
      },
      Latitude: {
        type: 'decimal',
        "default": 0
      },
      Longitude: {
        type: 'decimal',
        "default": 0
      }
    });

    return City;

  })(dsvdb.Model);

  models = {
    City: City
  };

  db = new dsvdb.Database('../testdata', models);

  console.log('starting');

  console.time('load');

  db.loadFiles('City', function(err, model) {
    console.timeEnd('load');
    return console.log(err, model.length);
  });

}).call(this);
