// Generated by CoffeeScript 1.8.0
(function() {
  var Fruit, dsvdb,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dsvdb = require('../index');

  Fruit = (function(_super) {
    __extends(Fruit, _super);

    function Fruit() {
      return Fruit.__super__.constructor.apply(this, arguments);
    }

    Fruit.prototype.model = 'Fruit';

    Fruit.defaults({
      handle: {
        type: 'string',
        "default": ''
      },
      name: {
        type: 'string',
        "default": ''
      },
      price: {
        type: 'decimal',
        "default": 0
      }
    });

    return Fruit;

  })(dsvdb.Collection);

  dsvdb.loadFiles({
    collection: Fruit,
    separator: ',',
    path: '../testdata/Fruit'
  }, function(err, collection) {
    console.log(err);
    console.log('--------------------');
    return console.log(collection);
  });

}).call(this);
